/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as IslamicEducationRouteImport } from './routes/islamic-education'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as AcademicsRouteImport } from './routes/academics'
import { Route as AboutRouteImport } from './routes/about'
import { Route as FacultyRouteRouteImport } from './routes/faculty/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminGalleryRouteImport } from './routes/admin/gallery'
import { Route as AdminFacultyAccountsRouteImport } from './routes/admin/faculty-accounts'
import { Route as AdminFacultyRouteImport } from './routes/admin/faculty'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminClassMaterialsRouteImport } from './routes/admin/class-materials'
import { Route as AdminAdmissionsRouteImport } from './routes/admin/admissions'
import { Route as FacultyPortalRouteRouteImport } from './routes/faculty/portal/route'
import { Route as FacultyPortalIndexRouteImport } from './routes/faculty/portal/index'
import { Route as FacultyPortalProfileRouteImport } from './routes/faculty/portal/profile'
import { Route as FacultyPortalMaterialsRouteImport } from './routes/faculty/portal/materials'

const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const IslamicEducationRoute = IslamicEducationRouteImport.update({
  id: '/islamic-education',
  path: '/islamic-education',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsRoute = AcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultyRouteRoute = FacultyRouteRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminGalleryRoute = AdminGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFacultyAccountsRoute = AdminFacultyAccountsRouteImport.update({
  id: '/faculty-accounts',
  path: '/faculty-accounts',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFacultyRoute = AdminFacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminClassMaterialsRoute = AdminClassMaterialsRouteImport.update({
  id: '/class-materials',
  path: '/class-materials',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAdmissionsRoute = AdminAdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const FacultyPortalRouteRoute = FacultyPortalRouteRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => FacultyRouteRoute,
} as any)
const FacultyPortalIndexRoute = FacultyPortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FacultyPortalRouteRoute,
} as any)
const FacultyPortalProfileRoute = FacultyPortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => FacultyPortalRouteRoute,
} as any)
const FacultyPortalMaterialsRoute = FacultyPortalMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => FacultyPortalRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/faculty': typeof FacultyRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/islamic-education': typeof IslamicEducationRoute
  '/students': typeof StudentsRoute
  '/faculty/portal': typeof FacultyPortalRouteRouteWithChildren
  '/admin/admissions': typeof AdminAdmissionsRoute
  '/admin/class-materials': typeof AdminClassMaterialsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/faculty': typeof AdminFacultyRoute
  '/admin/faculty-accounts': typeof AdminFacultyAccountsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/faculty/portal/materials': typeof FacultyPortalMaterialsRoute
  '/faculty/portal/profile': typeof FacultyPortalProfileRoute
  '/faculty/portal/': typeof FacultyPortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/faculty': typeof FacultyRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/islamic-education': typeof IslamicEducationRoute
  '/students': typeof StudentsRoute
  '/admin/admissions': typeof AdminAdmissionsRoute
  '/admin/class-materials': typeof AdminClassMaterialsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/faculty': typeof AdminFacultyRoute
  '/admin/faculty-accounts': typeof AdminFacultyAccountsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/faculty/portal/materials': typeof FacultyPortalMaterialsRoute
  '/faculty/portal/profile': typeof FacultyPortalProfileRoute
  '/faculty/portal': typeof FacultyPortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/faculty': typeof FacultyRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/islamic-education': typeof IslamicEducationRoute
  '/students': typeof StudentsRoute
  '/faculty/portal': typeof FacultyPortalRouteRouteWithChildren
  '/admin/admissions': typeof AdminAdmissionsRoute
  '/admin/class-materials': typeof AdminClassMaterialsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/faculty': typeof AdminFacultyRoute
  '/admin/faculty-accounts': typeof AdminFacultyAccountsRoute
  '/admin/gallery': typeof AdminGalleryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/faculty/portal/materials': typeof FacultyPortalMaterialsRoute
  '/faculty/portal/profile': typeof FacultyPortalProfileRoute
  '/faculty/portal/': typeof FacultyPortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/faculty'
    | '/about'
    | '/academics'
    | '/admissions'
    | '/contact'
    | '/gallery'
    | '/islamic-education'
    | '/students'
    | '/faculty/portal'
    | '/admin/admissions'
    | '/admin/class-materials'
    | '/admin/dashboard'
    | '/admin/faculty'
    | '/admin/faculty-accounts'
    | '/admin/gallery'
    | '/admin/login'
    | '/admin/settings'
    | '/faculty/portal/materials'
    | '/faculty/portal/profile'
    | '/faculty/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/faculty'
    | '/about'
    | '/academics'
    | '/admissions'
    | '/contact'
    | '/gallery'
    | '/islamic-education'
    | '/students'
    | '/admin/admissions'
    | '/admin/class-materials'
    | '/admin/dashboard'
    | '/admin/faculty'
    | '/admin/faculty-accounts'
    | '/admin/gallery'
    | '/admin/login'
    | '/admin/settings'
    | '/faculty/portal/materials'
    | '/faculty/portal/profile'
    | '/faculty/portal'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/faculty'
    | '/about'
    | '/academics'
    | '/admissions'
    | '/contact'
    | '/gallery'
    | '/islamic-education'
    | '/students'
    | '/faculty/portal'
    | '/admin/admissions'
    | '/admin/class-materials'
    | '/admin/dashboard'
    | '/admin/faculty'
    | '/admin/faculty-accounts'
    | '/admin/gallery'
    | '/admin/login'
    | '/admin/settings'
    | '/faculty/portal/materials'
    | '/faculty/portal/profile'
    | '/faculty/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  FacultyRouteRoute: typeof FacultyRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AcademicsRoute: typeof AcademicsRoute
  AdmissionsRoute: typeof AdmissionsRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  IslamicEducationRoute: typeof IslamicEducationRoute
  StudentsRoute: typeof StudentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/islamic-education': {
      id: '/islamic-education'
      path: '/islamic-education'
      fullPath: '/islamic-education'
      preLoaderRoute: typeof IslamicEducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics': {
      id: '/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof AcademicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculty': {
      id: '/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof FacultyRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/gallery': {
      id: '/admin/gallery'
      path: '/gallery'
      fullPath: '/admin/gallery'
      preLoaderRoute: typeof AdminGalleryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/faculty-accounts': {
      id: '/admin/faculty-accounts'
      path: '/faculty-accounts'
      fullPath: '/admin/faculty-accounts'
      preLoaderRoute: typeof AdminFacultyAccountsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/faculty': {
      id: '/admin/faculty'
      path: '/faculty'
      fullPath: '/admin/faculty'
      preLoaderRoute: typeof AdminFacultyRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/class-materials': {
      id: '/admin/class-materials'
      path: '/class-materials'
      fullPath: '/admin/class-materials'
      preLoaderRoute: typeof AdminClassMaterialsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/admissions': {
      id: '/admin/admissions'
      path: '/admissions'
      fullPath: '/admin/admissions'
      preLoaderRoute: typeof AdminAdmissionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/faculty/portal': {
      id: '/faculty/portal'
      path: '/portal'
      fullPath: '/faculty/portal'
      preLoaderRoute: typeof FacultyPortalRouteRouteImport
      parentRoute: typeof FacultyRouteRoute
    }
    '/faculty/portal/': {
      id: '/faculty/portal/'
      path: '/'
      fullPath: '/faculty/portal/'
      preLoaderRoute: typeof FacultyPortalIndexRouteImport
      parentRoute: typeof FacultyPortalRouteRoute
    }
    '/faculty/portal/profile': {
      id: '/faculty/portal/profile'
      path: '/profile'
      fullPath: '/faculty/portal/profile'
      preLoaderRoute: typeof FacultyPortalProfileRouteImport
      parentRoute: typeof FacultyPortalRouteRoute
    }
    '/faculty/portal/materials': {
      id: '/faculty/portal/materials'
      path: '/materials'
      fullPath: '/faculty/portal/materials'
      preLoaderRoute: typeof FacultyPortalMaterialsRouteImport
      parentRoute: typeof FacultyPortalRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAdmissionsRoute: typeof AdminAdmissionsRoute
  AdminClassMaterialsRoute: typeof AdminClassMaterialsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminFacultyRoute: typeof AdminFacultyRoute
  AdminFacultyAccountsRoute: typeof AdminFacultyAccountsRoute
  AdminGalleryRoute: typeof AdminGalleryRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAdmissionsRoute: AdminAdmissionsRoute,
  AdminClassMaterialsRoute: AdminClassMaterialsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminFacultyRoute: AdminFacultyRoute,
  AdminFacultyAccountsRoute: AdminFacultyAccountsRoute,
  AdminGalleryRoute: AdminGalleryRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSettingsRoute: AdminSettingsRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface FacultyPortalRouteRouteChildren {
  FacultyPortalMaterialsRoute: typeof FacultyPortalMaterialsRoute
  FacultyPortalProfileRoute: typeof FacultyPortalProfileRoute
  FacultyPortalIndexRoute: typeof FacultyPortalIndexRoute
}

const FacultyPortalRouteRouteChildren: FacultyPortalRouteRouteChildren = {
  FacultyPortalMaterialsRoute: FacultyPortalMaterialsRoute,
  FacultyPortalProfileRoute: FacultyPortalProfileRoute,
  FacultyPortalIndexRoute: FacultyPortalIndexRoute,
}

const FacultyPortalRouteRouteWithChildren =
  FacultyPortalRouteRoute._addFileChildren(FacultyPortalRouteRouteChildren)

interface FacultyRouteRouteChildren {
  FacultyPortalRouteRoute: typeof FacultyPortalRouteRouteWithChildren
}

const FacultyRouteRouteChildren: FacultyRouteRouteChildren = {
  FacultyPortalRouteRoute: FacultyPortalRouteRouteWithChildren,
}

const FacultyRouteRouteWithChildren = FacultyRouteRoute._addFileChildren(
  FacultyRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  FacultyRouteRoute: FacultyRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AcademicsRoute: AcademicsRoute,
  AdmissionsRoute: AdmissionsRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  IslamicEducationRoute: IslamicEducationRoute,
  StudentsRoute: StudentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
